app/urls.py
from django.urls import path
from app import views
app_name="app"

urlpatterns = [
    path('profile/',views.profile,name="profile"),
    path('login/', views.login, name="login"),
    path('sign_up/', views.sign_up, name="signup"),
]

practice/urls.py
from django.contrib import admin
from django.urls import path,include
import app
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',views.base,name="base"),
    path('',views.home,name="home"),
    path('app/',include("app.urls")),
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.


def base(request):
    return render(request,"base.html")

def home(request):
    return render(request,"app/home.html")

def login(request):
    return render(request,"app/login.html")

def sign_up(request):
    return render(request,"app/sign_up.html")

def profile(request):
    name="Hrushikesh"
    return render(request,"app/profile.html",{'name':name})

templates/app/home.html
{% extends "base.html" %}

{% block title %}
    <title>Home Page</title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to Home page</h1>
        </div>
      </div>
{% endblock %}

templates/app/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    <h1>LOGIN</h1>
    <form class="bigil" action="http://127.0.0.1:8000/" onsubmit="login()">
        <table>
            <tr>
                <td>Username :</td>
                <td>
                    <input type="text" placeholder="Enter your Username">
                </td>
            </tr>
            <tr>
                <td>Password :</td>
                <td>
                    <input type="password" placeholder="Enter your Password">
                </td>
            </tr>
        </table>
        
        <button class="button button">Log In</button>
    </form>
    <script>
        function login() {
     location.href = 'http://127.0.0.1:8000/';
    }
        </script>
</body>
</html>

templates/app/profile.html
{% extends "base.html" %}

{% block title %}
    <title>Profile Page</title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to {{name}} Profile page</h1>
        </div>
      </div>
      <div class="container">
        <div class="jumbotron">
            <p>My self HRUSHIKESH CHIKKERUR, I am Quick learner,Eager to learn new technologies and 
              methodologies,Willing to innovate the new things which can improve the existing 
              technologies and having a good communication skill.</p>
            <p>Now I have learnt new programming language "PYTHON" and Web technologies like 
              "HTML5,CSS,JAVASCRIPT,BOOTSTRAP" and also database query language "MYSQL", which 
              helps to improve my knowledge on some of the existing technologies.</p>  
        </div>
      </div>
{% endblock %}

templates/app/sign_up.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Sign Up</title>
	<link rel="stylesheet" href="{% static 'css/sign-up.css' %}">
</head>
<body>
	<h1>Sign Up</h1>
	<form class="bigil" onsubmit="signin()" action="http://127.0.0.1:8000/app/login/">
		<table>
			<tr>
				<td>First Name : </td>
				<td>
					<input type="text" name="your first name" id="fn">
				</td>
				<td>Last Name :</td>
				<td>
					<input type="text" name="Enter your last name" id="ln">
				</td>
			</tr>
			<tr>
				<td>Username :</td>
				<td>
					<input type="text" name="Enter your username" id="us">
				</td>
				<td>Password : </td>
				<td>
					<input type="password" name="Enter your password" id="pass">
				</td>
			</tr>
			<tr>
				<td>Email Address :</td>
				<td>
					<input type="email" name="Enter your email address" id="ed">
				</td>
				<td>Phone/Contact Number:</td>
				<td>
					<input type="number" name="Enter your number" id="pn">
				</td>
			</tr>

		</table>
		<button class="button button">Sign Up</button>
	</form>
	<script>
        function signin() {
     location.href = 'http://127.0.0.1:8000/app/login/';
    }
    </script>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Base Page</title> 
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
  {% include "partials/_topbar.html" %}  
  {% include "partials/_navbar.html" %}

    {% block content %}
      <div class="container">
        <div class="jumbotron">
          <h1>Welcome to base page</h1>
          
        </div>
      </div>
    {% endblock %}
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
  {% include "partials/_footer.html" %}

</body>
</html>

templates/partials/_footer.html
<!--footer-->

<div class="alert alert-primary" role="alert" id="foot">
    <marquee>ROCK ON!!!!! ROCK N ROLL !!!!!! ROCK ON!!!!! ROCK N ROLL !!!!!! 
        ROCK ON!!!!! ROCK N ROLL !!!!!! Enjoy what you are looking into the page !!!!!!! 
        ROCK ON!!!!! ROCK N ROLL !!!!!! ROCK ON!!!!! ROCK N ROLL !!!!!! 
        ROCK ON!!!!! ROCK N ROLL !!!!!!</marquee>
  </div>

templates/partials/_navbar.html
<!-- navbar -->

<div class="container">
    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:profile' %}">Profile</a>
        </li>      
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:login' %}">Login</a>
        </li> 
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:signup' %}">Sign_Up</a>
        </li> 
    </ul>
  </div>

templates/partials/_topbar.html
<!--topbar-->

<div class="alert alert-secondary" role="alert" id="top">
    <marquee>ROCK ON!!!!! ROCK N ROLL !!!!!! ROCK ON!!!!! ROCK N ROLL !!!!!! 
        ROCK ON!!!!! ROCK N ROLL !!!!!! Enjoy what you are looking into the page !!!!!!! 
        ROCK ON!!!!! ROCK N ROLL !!!!!! ROCK ON!!!!! ROCK N ROLL !!!!!! 
        ROCK ON!!!!! ROCK N ROLL !!!!!!</marquee>
 </div>